jobs:
  check-commit-message:
    uses: dbeaver/dbeaver/.github/workflows/reused-commit-msgs-validator.yml@devel
name: Commit Message Validation
on:
  repository_dispatch:
    types: trigger-ga___commit-msgs-validator.yml
