jobs:
  validate-commit-message:
    name: Validate Commit Message
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Validate Commit Message Content
      uses: gsactions/commit-message-checker@v1
      with:
        error: 'Each commit message must begin with GitHub or Jira ticket reference.
          Like:

          *  #<issue_number>

          *  repo#<issue_number>

          *  org/repo#<issue_number>

          *  DB-Number (Jira)

          *  CB-Number (Jira)


          For how to rename your commit message, follow this GitHub Doc:

          https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message'
        excludeDescription: 'true'
        excludeTitle: 'true'
        pattern: ^(#\d{3,6}|((Merge|dbeaver|cloudbeaver).+?#\d{3,6})|((DB-|CB-|web-)\d+)).*$
name: Check Commit Message
on:
  repository_dispatch:
    types: trigger-ga___reused-commit-msgs-validator.yml
